name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
      - uses: go-semantic-release/action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          changelog-file: CHANGELOG.md
          changelog-generator-opt: "emojis=true;"
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "docs(changelog): update changelog after release"
          file_pattern: CHANGELOG.md